version: '3'
services:
  client:
    build: client
    ports:
     - "80:80"
    volumes:
     - ./client:/app
    environment: 
     - API_HOST=localhost
     - API_PORT=8080
  api:
    build: api
    ports:
     - "8080:3000"
    volumes:
     - ./api:/app
